<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LinkedIn</name>
   <tag></tag>
   <elementGuidId>db0cdd25-7bae-4fc7-a541-3f946d61525f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']/footer/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.social_linkedin > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fbddca4-89bf-4504-a9e5-a51e52eefe75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.linkedin.com/company/sauce-labs/</value>
      <webElementGuid>b3e0d00c-9456-4e27-a5c9-daa06ce4e989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9c1f6836-8012-4689-ab28-54b1f62a7653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>0cf332e9-8738-4a90-a411-a83cd0c633d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>social-linkedin</value>
      <webElementGuid>227c1a83-baf5-40df-9568-1dd7f40de735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LinkedIn</value>
      <webElementGuid>6c79f47e-b82b-4d54-829a-d09bfc5de6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)/footer[@class=&quot;footer&quot;]/ul[@class=&quot;social&quot;]/li[@class=&quot;social_linkedin&quot;]/a[1]</value>
      <webElementGuid>78304027-d38a-4fd7-8fbd-a4c01dae7342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']/footer/ul/li[3]/a</value>
      <webElementGuid>cbf06d67-db35-4948-960a-05050c8f62ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LinkedIn')]</value>
      <webElementGuid>77972629-137a-4aa3-b23b-d0fd3daad2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::a[1]</value>
      <webElementGuid>a8a012b3-8222-47ab-aeb6-587593b656f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/following::a[2]</value>
      <webElementGuid>6d5e9f24-d865-4254-b4cf-36f5e1fd51e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LinkedIn']/parent::*</value>
      <webElementGuid>46a88008-3fca-42fd-a3d0-aae18504ccd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.linkedin.com/company/sauce-labs/')]</value>
      <webElementGuid>a7d11939-0698-407a-be4e-93baa4b2c113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>bfcda4cd-5e0e-4a95-b53f-345cbf816ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.linkedin.com/company/sauce-labs/' and (text() = 'LinkedIn' or . = 'LinkedIn')]</value>
      <webElementGuid>98654400-cb92-4c5d-8862-98397b92c234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
