<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>footer_bar</name>
   <tag></tag>
   <elementGuidId>7276b544-ed52-47af-9347-e847fca86edc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']/footer</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>footer.footer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>footer</value>
      <webElementGuid>8e8ac7a6-ecad-4e15-8201-626f12daa85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer</value>
      <webElementGuid>4ff2f647-0371-4657-8a36-5cb4c4edb732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>footer</value>
      <webElementGuid>0a100ec6-ea96-4590-8951-762f18ff0ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TwitterFacebookLinkedIn© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy</value>
      <webElementGuid>0d5acdff-a6bd-442e-a7b5-06c8b8847af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)/footer[@class=&quot;footer&quot;]</value>
      <webElementGuid>c0ccdfc4-1b20-43f2-82d6-7068ebfe3266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']/footer</value>
      <webElementGuid>a5ebbb39-ebbe-4cd2-9e72-b9f0044457e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::footer[1]</value>
      <webElementGuid>c30550be-4800-48b3-ad16-d78fc0d99be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/following::footer[1]</value>
      <webElementGuid>19c83abc-ea6e-4d58-8bac-4ecc1d88951f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer</value>
      <webElementGuid>99c313a8-0238-4c01-8836-937ad3908d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//footer[(text() = 'TwitterFacebookLinkedIn© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy' or . = 'TwitterFacebookLinkedIn© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy')]</value>
      <webElementGuid>87ef6589-3dab-4a64-8481-ec5e5a85c5ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
