<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_footer</name>
   <tag></tag>
   <elementGuidId>2806049c-88eb-48cf-9ca9-ca91c1fe4005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']/footer/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footer_copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0179b83d-40c8-4212-afe2-aecae4f46aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_copy</value>
      <webElementGuid>86878a94-b52a-4ccd-8675-d6babe808737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>footer-copy</value>
      <webElementGuid>3fe06744-8843-400e-8600-51bd8729363c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy</value>
      <webElementGuid>8a58f09c-e00f-4378-81c4-d4d320347da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)/footer[@class=&quot;footer&quot;]/div[@class=&quot;footer_copy&quot;]</value>
      <webElementGuid>341b5ed0-f353-4cdd-9cfd-af4aae6de28f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']/footer/div</value>
      <webElementGuid>0dd98305-54cb-4881-9869-f603c9313a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LinkedIn'])[1]/following::div[1]</value>
      <webElementGuid>8b1d0cd5-6433-48df-8779-8c90c8e05b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::div[1]</value>
      <webElementGuid>738df607-0cde-4d09-9c7e-0d51dba970d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='©']/parent::*</value>
      <webElementGuid>00b0fc55-ef3a-4eff-ae65-63a8f5aeec34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div</value>
      <webElementGuid>713bb1ab-4a2b-476b-953d-4d69f7be59bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy' or . = '© 2024 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy')]</value>
      <webElementGuid>052a340d-5cd5-473a-9a74-07b1d174e20a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
